--CREATE DATABASE RPA_LOGS
USE RPA_LOGS 
GO

CREATE TABLE CLIENTE (
    UUID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
    NOME VARCHAR(300) NOT NULL,
    EMAIL_CONTATO VARCHAR(150) NULL,
    IDENTIFICADOR VARCHAR(300) NOT NULL,
)

CREATE TABLE ROBO (
    UUID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
    NOME VARCHAR(300) NOT NULL,
    ATIVO SMALLINT NOT NULL,
    IDENTIFICADOR VARCHAR(300) NOT NULL,
    UUID_CLIENTE UNIQUEIDENTIFIER NOT NULL,

    CONSTRAINT FK_ROBO_CLIENTE FOREIGN KEY (UUID_CLIENTE) REFERENCES CLIENTE (UUID)
)

CREATE TABLE EXECUCAO (
    UUID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
    UUID_ROBO UNIQUEIDENTIFIER NOT NULL,
    INICIO_EXECUCAO DATETIME NOT NULL,
    FIM_EXECUCAO DATETIME NULL,
    STATUS VARCHAR(50), --ERRO, SUCESSO, EM_ANDAMENTO

    CONSTRAINT FK_EXECUCAO_ROBO FOREIGN KEY(UUID_ROBO) REFERENCES ROBO(UUID)
)

CREATE TABLE EXECUCAO_LOG (
    UUID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
    UUID_EXECUCAO UNIQUEIDENTIFIER NOT NULL,
    NUMERO_PROCESSO INTEGER NOT NULL,
    PROCESSO VARCHAR(500) NOT NULL,
    INICIO_EXECUCAO DATETIME NOT NULL,
    FIM_EXECUCAO DATETIME NULL,
    CATEGORIA VARCHAR(50) NOT NULL,
    STATUS VARCHAR(50) NOT NULL,
    MENSAGEM VARCHAR(500) NULL,

    CONSTRAINT FK_LOG_EXECUCAO FOREIGN KEY(UUID_EXECUCAO) REFERENCES EXECUCAO(UUID),
)